### ISSUE TITLE
[Privacy] Spell out the possible loss of privacy guarantees 

### ISSUE THREAD

**Issue by sudheesh001** [tfpauly/draft-pauly-adaptive-dns-privacy#109]
The current implementation doesn't restrict users from using an Oblivious Proxy and an Oblivious Target run by the same organization. Doing so would allow the organization to put together the relevant information of the client by IP address and loses the privacy guarantees this was intended for.

A user however could use the Proxy and Target provided by the same organization if the user trusts the organization with respect to deleting or not storing the Client IP address information or leaking it to trackers. Such usage depends heavily on the users' personal privacy model.

I think it'd be nice to spell out these possible considerations in the draft for privacy guarantees and when ODOH would be effective.

**Comment by chris-wood** [comment]
This is discussed in the security considerations where we discuss the model. (We assume the adversary can compromise P or T but not both.) Closing!
