### ISSUE TITLE
[Privacy] Detail the ideal expected way of usage for Oblivious DOH

### ISSUE THREAD

**Issue by sudheesh001** [tfpauly/draft-pauly-adaptive-dns-privacy#110]
The ideal expectation from users is to choose an Oblivious Proxy and an Oblivious Target from different organizations with the base assumption that both the organizations are independent and operate correctly or do not collude to match the client IP address at the proxy to the encrypted query.

As indicated in #109 as a broader issue, it is probably necessary to detail out this information and possibility of the privacy bets being off if both the proxy and target used belong to the same organization.

**Comment by chris-wood** [comment]
This is covered in the security considerations, where we assume the adversary can compromise the proxy or target, but not both. (Compromising both is tantamount to colluding.)
