### ISSUE TITLE
Explore mechanisms to audit proxies or rank the proxies by their reliability/privacy guarantees

### ISSUE THREAD

**Issue by sudheesh001** [tfpauly/draft-pauly-adaptive-dns-privacy#112]
This issue probably dovetails into the discovery mechanism of the proxies and targets in ODOH. In order to prevent flooding issues (#108) it's probably necessary to establish some means of trust in the proxies through transparency or monitoring similar to CT infrastructure which can indicate history of breaches/compromise, reliability/uptime of a proxy or a target.

An auditing based approach seems incredibly difficult for something like this but maybe there's a need for constant probing or honeypots? At a high level the problem seems to be the following:

> How do we prove/disprove that the proxy is not sending client information elsewhere?

**Comment by chris-wood** [comment]
While useful, this seems like a larger ecosystem question beyond the scope of the ODoH protocol, so I'm closing.
