### ISSUE TITLE
HTTP server push clarification

### ISSUE THREAD

**Issue by JoGSal** [tfpauly/draft-pauly-adaptive-dns-privacy#120]
draft-pauly-add-resolver-discovery

Section 3.2 "servers MAY use HTTP Server Push to deliver the signed SVCB answers prior to requests being made"
What data would be in cleartext in HTTP server push requests?

**Comment by tfpauly** [comment]
This wouldn't be cleartext, but in the normal DoH connection. Is there something that mentions cleartext?

**Comment by JoGSal** [comment]
No, it was my mistaken interpretation of what delivering via HTTP server push would entail
