### ISSUE TITLE
Add alt-svc parameter for ODoH key distribution

### ISSUE THREAD

**Issue by tanyav2** [tfpauly/draft-pauly-adaptive-dns-privacy#124]
Currently, the ODoH spec states that public key distribution should be done via HTTPSSVC records, but doesn't detail any other information. Perhaps we can make some details concrete.

The `alt-svc` (an extension to the HTTPSSVC DNS record) parameter can be `odohkeys` in a similar vein as `esnikeys` mentioned here: https://tools.ietf.org/html/draft-nygren-httpbis-httpssvc-01#section-7.1 and the public key can be encoded in `base64` format similar to `esnikeys`.

**Comment by tfpauly** [comment]
The references actually need to be updated to https://tools.ietf.org/html/draft-ietf-dnsop-svcb-https-01. And yes, the keys should follow a similar format to `echconfig`.

@chris-wood  thoughts?

**Comment by chris-wood** [comment]
Perhaps an `odohconfig` key and public key structure that matches `echconfig` would work?

**Comment by chris-wood** [comment]
This is now resolved. Closing.
