### ISSUE TITLE
Whitelist -> Allowlist

### ISSUE THREAD

**Issue by FredericJacobs** [tfpauly/draft-pauly-adaptive-dns-privacy#131]
Whitelist could be replaced with allow list to make the language of the spec more inclusive.

```
blacklist/whitelist (n., v.)
Don’t use. Instead, use an alternative that’s appropriate to the context, such as deny list/allow list or unapproved list/approved list.
```
https://help.apple.com/applestyleguide/#/apsg1a3a0436?sub=apd9aaca4623

**Comment by tfpauly** [comment]
I think this is only used on our older draft, which we may just remove. Thanks!

**Comment by chris-wood** [comment]
This should be done now. Closing.
