### ISSUE TITLE
Clarify use of address hints 

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/draft-pauly-adaptive-dns-privacy#145]
From Ben: 
> "These address hints ... avoid additional DNS lookup for the A and AAAA records of the Encrypted Resolver name."

Strictly speaking, a compliant SVCB client is expected to perform the additional lookups anyway.  The hints just avoid a delay while those queries complete.  If you think it's important to "skip" those followup queries, we would have to make a deeper change.  Otherwise, you could say "avoid *waiting for* DNS lookup...".

**Comment by mstojens** [comment]
Issue migrated to DDR repo: https://github.com/ietf-wg-add/draft-ietf-add-ddr/issues/5
