### ISSUE TITLE
Update HPKE to draft-06

### ISSUE THREAD

**Issue by tanyav2** [tfpauly/draft-pauly-adaptive-dns-privacy#148]
Peter Wu noted that the draft uses [HPKE draft-05](https://tools.ietf.org/html/draft-pauly-dprive-oblivious-doh-02#ref-I-D.irtf-cfrg-hpke). Given that both implementations the go and rust implementations of HPKE now support HPKE draft-06, it makes sense to update the hpke version to draft-06.

@Lekensteyn
@chris-wood

**Comment by chris-wood** [comment]
This is already done: https://tfpauly.github.io/draft-pauly-adaptive-dns-privacy/draft-pauly-dprive-oblivious-doh.html#section-10

**Comment by Lekensteyn** [comment]
Is there a timeline for releasing draft -03?

**Comment by chris-wood** [comment]
I'll cut a new version today. @tfpauly, any objections?

**Comment by tfpauly** [comment]
@chris-wood go for it!
