### ISSUE TITLE
[ODoH] Add EDNS(0) client subnet guidance

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-pauly-adaptive-dns-privacy#149]
Clients technically can send their subnet in encrypted queries, if they want rough geo-based responses from targets. We should at least discuss this, given recent feedback on the topic during IETF 109.

**Comment by tfpauly** [comment]
This is technically already allowed, just needs to be spelled out.

**Comment by chris-wood** [comment]
@tfpauly can you propose text for this?
