### ISSUE TITLE
Promote proxy URI template 

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-pauly-adaptive-dns-privacy#150]
It's hidden in an example, and probably needs to be made more clear. We could also use some discussion about proxies using this template to forward, vs more typical web proxies forwarding to targets.

**Comment by tfpauly** [comment]
This is described in section 4.1, but happy to highlight even more:

Oblivious DoH queries are created by the Client, and sent to the Proxy. Requests to the Proxy indicate which DoH server to use as a Target by specifying two variables: "targethost", which indicates the host name of the Target server, and "targetpath", which indicates the path on which the Target's DoH server is running. See Section 4.2 for an example request.

**Comment by chris-wood** [comment]
Closing, since this is probably fine for now.
