### ISSUE TITLE
ODoH: Failure status codes

### ISSUE THREAD

**Issue by tanyav2** [tfpauly/draft-pauly-adaptive-dns-privacy#151]
Starting a discussion to figure out reasonable failure modes of the server:

1. Query cannot be deserialized into an `ObliviousDoHMessage` 
2. Unknown key ID of query 
3. Query cannot be parsed into a valid `ObliviousDoHQueryBody` (wrong message type, invalid tag while decrypting, other decryption failure etc)
4. DNS query resolution fails by the resolver
5. Response message cannot be created (this is an internal server error and should have nothing to do with the client)

I think we can give (1) and (3) the same error code 400, (4) can be 200 because for `NXDOMAIN` or `SERVFAIL`, DoH still serves 200, (5) can be 500, (2) can be 401 (which is used for invalid username/password). 

@tfpauly @chris-wood

**Comment by chris-wood** [comment]
The adjusted errors look good to me. (I had concerns about lumping 1+3 in with 4, but that's fixed.)

**Comment by tanyav2** [comment]
Great, I'll make a PR to update the draft.
