### ISSUE TITLE
DEER caching text

### ISSUE THREAD

**Issue by bemasc** [tfpauly/draft-pauly-adaptive-dns-privacy#155]
The text says

> If a caching forwarder consults multiple resolvers, it may be possible for it to cache records for the "resolver.arpa" Special Use Domain Name (SUDN) for multiple resolvers.

This is not true of any reasonable forwarder.  RRsets are atomic collections, and cannot be mixed from multiple sources.  Doing so would entirely break DNSSEC, for example.  Unless you know of a forwarder that exhibits this seriously broken behavior, I don't think it bears mentioning.

**Comment by mstojens** [comment]
Issue migrated to DDR repo: https://github.com/ietf-wg-add/draft-ietf-add-ddr/issues/6
