### ISSUE TITLE
Recommend limits

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-pauly-adaptive-dns-privacy#156]
The `ObliviousDoHMessage` format is quite flexible in how large the `key_id` and `encrypted_message` values are:

~~~
   struct {
      uint8  message_type;
      opaque key_id<0..2^16-1>;
      opaque encrypted_message<1..2^16-1>;
   } ObliviousDoHMessage;
~~~

We should recommend that proxies and targets enforce reasonable limits for these. For example, no DNS query will bump against the 2^16-1 length limit. 

While we're here, we should probably also reduce `key_id`'s allotted length to a single byte.

**Comment by tanyav2** [comment]
[XDR](https://tools.ietf.org/html/rfc4506) which seems to be the standard wireformat encoding says that `opaque` fields must have a 2 byte length encoding.

**Comment by chris-wood** [comment]
We use TLS encoding here, for what it's worth. We're not bound to any XDR-related rules.

**Comment by tanyav2** [comment]
Ah, I wasn't aware that was a separate encoding.

**Comment by tfpauly** [comment]
@chris-wood I'm fine with specifying limits on the value, but I think it's fine to leave the length fields being 2 bytes for consistency.
