### ISSUE TITLE
DEER: Clarification of SUDN

### ISSUE THREAD

**Issue by awfulhak** [tfpauly/draft-pauly-adaptive-dns-privacy#160]
The Special Use Domain Name (SUDN) ```resolver.arpa``` needs more clarification.  Specifically:
- Queries against the ```.arpa``` nameservers
  The draft should mention that ```.arpa``` is a delegated zone, currently served by the root nameservers.  Clients that query a resolver that is unaware of this requirement will "leak" queries to the root nameservers.
- When ```_dns.resolver.arpa/SVCB``` is not present in a resolver configuration
  Section 6.1 discusses how a forwarder should behave and suggests that results should not be cached other than for Equivalent Encrypted Resolvers under their control.  How is that determined?
  There is no discussion around a non-forwarding resolver's behaviour.  Should it return NODATA?
  Forwarding queries to ```_dns.resolver.arpa/SVCB``` will attempt to attach a client to an upstream resource's equivalent resolver.  If that equivalent resolver's cert doesn't include the forwarder, the client must reject the answer.  Is it not therefore the case that the forwarder caching behaviour is irrelevant?  All valid responses to this query must be equivalent to the forwarder itself.
- When ```_dns.resolver.arpa/SVCB``` is present in a resolver configuration
  I would suggest some clarification wording something like this: The expectation is that this record set will detail equivalent resolvers.  A client that chooses not to interact with any of these equivalent resolvers SHOULD continue to use the unencrypted resolver, honouring the SVCB TTL.  When the SVCB TTL expires, the client may choose to re-query in an attempt to discover newly available equivalents.

I would suggest (prefer?) changing the SUDN behaviour so that queries against it are __never__ sent upstream.  Resolvers (and forwarders) that do not have a configured ```_dns.resolver.arpa/SVCB``` RRset should return NODATA.  This would mean that ```resolver.arpa``` SUDN RRsets are always specific to the IP queried.

**Comment by tfpauly** [comment]
It may be good to model the advice after RFC8880, which defines ipv4only.arpa.

**Comment by tfpauly** [comment]
@mstojens can you help look at this?

**Comment by mstojens** [comment]
Issue migrated to DDR repo: https://github.com/ietf-wg-add/draft-ietf-add-ddr/issues/7
