### ISSUE TITLE
Clarification of expectations in certain NAT environments

### ISSUE THREAD

**Issue by vparla** [tfpauly/draft-pauly-adaptive-dns-privacy#161]
It would be helpful if there was a paragraph that described what the expected behavior is in certain NAT scenarios.

Since the IP address must be embedded in the TLS certificate, certain NAT scenarios could present a problem for this approach.

For example, if the assigned DNS IP addresses via DHCP are not the actual IP address(es) associated with the DNS service, there could be an issue.  How would such a deployment scenario be addressed?

**Comment by tfpauly** [comment]
Certainly worth a paragraph or note.

@vparla can you clarify exactly which NAT scenarios you're considering here? If the client is behind a NAT reaching out to a DNS resolver that is not behind the NAT, the client presumably is reaching out to the "real" IP address of the resolver. If the resolver is behind the NAT with the client, then that seems to be a case in which we'd expect it to simply have the same address as the unencrypted resolver?

**Comment by vparla** [comment]
@tfpauly.
So if the DHCP assigned DNS address(es) are NAT addresses instead of the actual DNS server addresses, what is the expected outcome?  It was unclear to me if this would work correctly as the client would see the NAT'd address(es) via DHCP and the certificate would hold the actual address(es), not the NAT'd address seen via DHCP.

So imagine NAT assigned address is 1.2.3.4 and actual address of DNS server is 4.5.6.7.  What would be the expected outcome here?  DNS from the client would got to 1.2.3.4:53 then be NAT'd to actual DNS server @ 4.5.6.7:53

Note this is an edge case for the most part, but possible.

**Comment by bemasc** [comment]
@vparla It sounds like you're describing a classic "DNS forwarder".  I don't think this matches typical usage of "NAT", which does not modify the server IP as observed by the client.

**Comment by vparla** [comment]
For the sake of this discussion, a DNS forwarder and a NAT can be viewed as roughly equivalent for this problem.
Client sees 1.2.3.4 and sends DNS to 1.2.3.4:53.  The actual DNS Server is 4.5.6.7 and the IP in the certificate are also 4.5.6.7

**Comment by bemasc** [comment]
This situation would not occur when using "NAT" according to the definition that I'm used to, but it is an important scenario to consider.

The current draft essentially rules this "out of scope".  As you observed, the upgrade will not occur in this configuration.

I have posted a (rather invasive) PR that would put this in-scope, with various safeguards to prevent unauthorized redirection: #147.

**Comment by vparla** [comment]
I am happy with it just being clearly articulated in terms of the scenario and the outcome.  
thanks for looking at it.

**Comment by mstojens** [comment]
Issue has been migrated to DDR repo: https://github.com/ietf-wg-add/draft-ietf-add-ddr/issues/8
