### ISSUE TITLE
Provide guidance about which status codes should be forwarded

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/draft-pauly-adaptive-dns-privacy#174]
Section 4.3 should clarify that only 2xx, 4xx, and 5xx response codes should be forwarded un-modified. (And even some 4xx response codes such as authentication-required may not make sense to relay but would need to be handled by the proxy.) The important one is that 1xx should never be relayed back as there-be-dragons.

**Comment by chris-wood** [comment]
Do you want to take this, or shall I?
