### ISSUE TITLE
[ODoH] how is path specified in SVCB RR?

### ISSUE THREAD

**Issue by enygren** [tfpauly/draft-pauly-adaptive-dns-privacy#177]
The SVCB record specification only contains the key and not the targetpath.  Ideally we'd reuse something from one of the DoH/DPRIVE/etc SVCB specs for this rather than creating a new SvcParamKey.

**Comment by tfpauly** [comment]
Correct, I agree this shouldn't define a new key for the path, but should rely on the encoding for DoH resolvers from draft-schwartz-svcb-dns.

**Comment by chris-wood** [comment]
This is no longer part of the spec, so I think we can close this out.
