### ISSUE TITLE
Separating the proxy pool from the target servers

### ISSUE THREAD

**Issue by mcmanus** [tfpauly/draft-pauly-adaptive-dns-privacy#34]
The document currently requires every designated doh server also be willing to act as a proxy server and target server.. this is tacitly a commitment to serve arbitrary amounts of recursive traffic in order to be able to authoritatively serve any domain over adaptive dns.

I expect that to be too much to ask of many folks to be successful.

And even among the folks that can offer that kind of service, they might reasonably want to provision it into different origins and infrastructures than they use for the authoritative designated doh server traffic.

The lack of quality control would also be a factor.

I suggest we filter the potential obfuscating servers by a new 'isProxy' attribute on their signed DOHNS RRs. Further,. we can bootstrap the system with a set of well known Proxies and Targets downloadable from a well known URL: https://www.doh-root-servers.net/proxyList - each proxy in that list would need a corresponding DOHNS with the isProxy attribute. It seems that URL could be looked up in a privacy insensitive way.

**Comment by chris-wood** [comment]
@mcmanus, @tfpauly, @erickinnear, is there still something to be done here? Can we close this?

**Comment by chris-wood** [comment]
@tfpauly I think we can close this out as overcome by events.

**Comment by tfpauly** [comment]
Agreed
