### ISSUE TITLE
Clarify the cipher suite for the symmetric key

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/draft-pauly-adaptive-dns-privacy#55]
The ODOH document says the cipher suite is passed by the client along with the symmetric key, but the struct doesn't seem to include this. Also, is there any negotiation of this? What if a suite becomes deprecated?

**Comment by chris-wood** [comment]
Also cite RFC8446 for TLS syntax.

**Comment by tfpauly** [comment]
The RFC8446 is already referenced, actually!
