### ISSUE TITLE
Consider path-based proxying method

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/draft-pauly-adaptive-dns-privacy#64]
From @enygren:

 I really, really do NOT like how :authority is having its meaning
 altered in the ODNS draft.  This breaks HTTP semantics and this
 breaks a bunch of assumptions on how CDN servers do hostname-based
 service multiplexing.  It would require having separate IP addresses
 for DoH servers from CDN servers, for example.  (Which has worse
 privacy properties.)  I'd propose instead that ODNS followes adds
 some path elements.  For example:

    :method = POST
    :authority = dnsproxy.example.net
    :path = /dns-query?targethost=dnstarget.example.net&targetpath=/dns-query
    ...

 makes this be normal HTTPS semantics.  It also avoids problems if the
 proxy and target have different DoH template URI paths which
 I don't believe the current draft handles?

**Comment by tfpauly** [comment]
This also was how we ended up implementing out test GO server, as a note.

**Comment by mcmanus** [comment]
yeah - this is my fault. I basically agree with @enygren now. I'm not sure it breaks http semantics, but we can debate that in the bar.. it does make the doh service discovery ridiculously hard and we should avoid that.

would we define a new uri template with targethost and targetpath variables?

**Comment by tfpauly** [comment]
Cool, I'll do this change.

I don't think we need a new URI Template; I think you just use the normal template here
