### ISSUE TITLE
Oblivious Resolution isn't only for privacy-sensitive connections

### ISSUE THREAD

**Issue by chris-box** [tfpauly/draft-pauly-adaptive-dns-privacy#68]
> ## Oblivious Resolution
> 
> For all privacy-sensitive connection queries for names that do not correspond
> to a Designated DoH Server, the client SHOULD use Oblivious DoH to help
> conceal its IP address from eavesdroppers and untrusted resolvers.

We learn from the Hostname Resolution Algorithm that step 4, Oblivious Resolution, should be used for all queries, not just the ones that are privacy-sensitive. Therefore should we remove the term "privacy-sensitive" from the statement above?

The only difference with privacy-sensitive queries is how we respond to failure.

**Comment by tfpauly** [comment]
We can perhaps also loosen the algorithm; I think for non-privacy sensitive connections, the client MAY skip oblivious DoH.

**Comment by chris-box** [comment]
Agreed, yes the client should have the option, if it has reason to know that skipping may be better.

**Comment by tfpauly** [comment]
Addressed in 889f6ef
