### ISSUE TITLE
We should add an explanation about why having "sensitive" flows isn't a privacy risk

### ISSUE THREAD

**Issue by erickinnear** [tfpauly/draft-pauly-adaptive-dns-privacy#7]
We should add an explanation about why having "sensitive" flows isn't a privacy risk. 
Specifically, that information isn't visible off the device at all and can't be fingerprinted, so an attacker can't identify which flows should be targeted with extra energy. 

Only the non-sensitive flows get to be seen on the local network and there is no difference between a sensitive flow that didn't get queried and one that didn't exist.

(We should also make sure that this is true, current top risk seems to be that someone on the local network "i.e. the router itself" can see things that didn't ask it and never resulted in a connection, ideally those are still okay because other things that did resolve via a Web PvD even non-sensitive would look the same way if they reuse a connection)

**Comment by tfpauly** [comment]
Closing as this is fairly old, and referencing the old doc
