### ISSUE TITLE
Meaning of dnsZones element

### ISSUE THREAD

**Issue by MikeBishop** [tfpauly/draft-pauly-adaptive-dns-privacy#83]
During the DPrivE discussion, there was a lot of concern about having a field here that is an unproven (i.e. client still needs to validate separately) assertion of the server's authority over these domains.  Pushing the HTTPSSVC records will demonstrate the authority or not regardless, so this field as-is seems to provide little value.

I'd suggest that this element should instead reflect the server's _willingness_ to resolve names.  If the server is a full recursive, the value would be `.`, the entire DNS.  If the server is only willing to resolve specific zones, this provides a list of those zones.  This helps the client avoid sending requests which will be rejected, and discover additional recursives in the event that it wants to spread non-designated queries across many recursives to limit correlation.

**Comment by tfpauly** [comment]
Added some more text here in #115
