### ISSUE TITLE
Add section on performance cost

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-pauly-adaptive-dns-privacy#84]
A concise description of what ODoH requires (computation-wise) beyond normal DoH is probably warranted.

**Comment by mstojens** [comment]
Someone commented on the Jabber that having that same cost comparison with Tor itself would be interesting, and I agree. Either this can be clearly establised as a in-between option for those who want no specific DNS server to have their IP/query but aren't willing to commit to the costs of Tor, or we'll learn Tor is a cheaper solution (unlikely imo but having the costs written down will put it to rest).

**Comment by chris-wood** [comment]
We have a section that compares this against general tools like Tor. I don't think it makes sense to add more details. Closing as such. (If anyone disagrees, please comment!)
