### ISSUE TITLE
Allow recursive resolvers to use SVCB to advertise their own DoH URI

### ISSUE THREAD

**Issue by mstojens** [tfpauly/draft-pauly-adaptive-dns-privacy#86]
In the scenario where a stub resolver is configured to talk to recursive resolver X from DHCP, it can't use DoH until it has the URI for that server. If the recursive and the stub are both DoH and aDNS aware, there's no reason the recursive can't use the SVCB record to inform the client querying it over UDP 53 that it can upgrade to DoH by using a provided URI. 

While this isn't necessary for domain that have designated DoH resolvers, it would be nice for the stub to query for domains without designated DoH resolvers using DoH from an automatic network configuration. This will allow for easier DNS server configuration options as only the IP address will be required (from DHCP, UI, or otherwise) as has been historically true.

As discussed offline, this shouldn't claim ownership of any domain but should still be signed to ensure secure upgrading to DoH from classic DNS.

**Comment by mstojens** [comment]
In conversations with ISPs, it's come up that such a solution would need to address both the easier public IP scenario as well as the private IP scenario. For example, if the router is handing out local addresses over DHCP, how can that local DNS server recommend a public DoH server in a secure manner such that the device knows the issuer of the DHCP recommendation and the owner of the DoH server are the same entity in possession of the same keys?

**Comment by fl1ger** [comment]
Wrt to the private IP scenario there is IMHO still value to use the resolver on the CPE, when it connects securely to it's resolver (we've seen CPE vendors including DoT recently). The hard unsolved problem is how can we connect secure to the CPE (DoT might be easier then DoH there, as it doesn't require a URI).

**Comment by mstojens** [comment]
Based on that, I could imagine splitting this into two scenarios:

- CPE recommends a public DoH server: issue as originally described (need to advertise the URI in such a way that the CPE can be proven to have the same owner as the public DoH server)
- CPE recommends itself or another private/local entity, knowing it handles encrypted DNS to the public internet: use DoT locally as you describe

As I write this out, it seems to boil down to "use DoH for public addresses, and DoT for private addresses" as a public address can be securely verified in a TLS cert whereas a private address cannot.

**Comment by fl1ger** [comment]
Makes sense, the problem will be to authenticate the private local connection. One thought could be to forward the cert/public IP/URI/name to the requesting entity.

**Comment by mstojens** [comment]
This was addressed by adding section 5 to the newly split out discovery doc.
