### ISSUE TITLE
Refer to RFC5507 discussing why the SVCB record is preferable to alternatives

### ISSUE THREAD

**Issue by mstojens** [tfpauly/draft-pauly-adaptive-dns-privacy#89]
I'm sure there was plenty of thought here, but the justification for a new record (SVCB) versus other options under RFC5507 section 3 would be useful.

**Comment by tfpauly** [comment]
Notes:
- If a client cares about name privacy, it will likely support HTTPS records for ECH already
- HTTPS/SVCB is an existing type, and is designed to have extensible RRData
- To passively detect designations for names, we don't want to add new queries from the client (beyond A/AAAA/HTTPS) or rely on recursive resolver behavior
