### ISSUE TITLE
Use TLS cert for designation trust?

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/draft-pauly-adaptive-dns-privacy#92]
@mstojens writes:

Why can't we confirm Designated server ownership of a domain via the TLS cert? This could be an additional option in addition to DNSSEC signed SVCBs and the PvD option. I can't think of an attack vector where a forged SVCB would lead the client to the wrong Designated server, as either:

the server's cert isn't valid for the domain the SVCB advertised, and the client can discard the record, or
the server's cert is valid for the domain the SVCB advertised
Perhaps it wouldn't be the preferred model by some, but it may make adoption easier for clients and servers who don't support / haven't deployed DNSSEC and already do TLS cert validation but not PvD work.

**Comment by mstojens** [comment]
If it will help the discussion on this topic, I'd be happy to draft a PR illustrating this possibility.

**Comment by tfpauly** [comment]
Sure, that'd be useful to see written up!
