### ISSUE TITLE
Specify proxy->target validation

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-pauly-adaptive-dns-privacy#99]
Proxies should probably have some way of validating that a target can and is willing to receive data. The mechanics of this validation mechanism might vary depending on when and how often the validation must be done.

**Comment by Lekensteyn** [comment]
The current security considerations are quite client-focused:

> In order to avoid interception and modification of the information retrieved by clients using Adaptive DNS, all exchanges between clients and servers are performed over encrypted connections, e.g., TLS.
> 
> Malicious adversaries may block client connections to all DoH or Oblivious DoH services as a Denial-of-Service (DoS) measure. Clients which cannot connect to any proxy may, by local policy, fall back to unencrypted DNS if this occurs.

It should probably be expanded to consider the Oblivious DoH Proxy/Server aspects. Indeed, in its current form the proxy could be used to send arbitrary data to non-DoH services.

From the spec, it wasn't clear to me whether the proxy has to perform any form of validation, and what error code to return in case of errors. The "Provide a DoH Server" section could be extended to clarify that.

**Comment by chris-wood** [comment]
Some text was added to address this in #167. Closing.
